name: ESLint
on:
  push:
    paths:
      - "src/**"
      - ".eslintrc.*"
      - ".prettierrc"
      - ".eslintignore"
      - ".github/workflows/lint.yml"
      - "package.json"
      - "yarn.lock"
  pull_request_target:
  workflow_dispatch:

jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint:fix

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: src
          message: "chore(lint): auto-lint source code"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
